id = "lean4"
name = "Lean 4"
description = "Lean 4 support."
version = "0.1.0"
schema_version = 1
authors = ["owlx56 <owlx365@gmail.com>"]
repository = "https://github.com/owlx56/zed-lean4"
snippets = "snippets/lean 4.json"

[language_servers.lean4-lsp]
name = "Lean4 Language Server"
languages = ["Lean 4"]

[grammars.lean]
repository = "https://github.com/Julian/tree-sitter-lean"
rev = "efe6b87145608d12f5996bd7f0cf6095a0e82261"

[[capabilities]]
kind = "process:exec"
command = "*"
args = ["**"]
